[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "nltk>=3.9.1",
    "scikit-learn>=1.6.1",
    "sqlalchemy[asyncio]>=2.0.41",
    "uvicorn>=0.34.2",
]
